language: scala
scala:
- 2.11.7
jdk:
- oraclejdk8

sudo: false

cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/"

script:
- sbt ++$TRAVIS_SCALA_VERSION mdocValidate
after_success:
- bash <(curl -s https://codecov.io/bash)

before_deploy:
- sbt ++$TRAVIS_SCALA_VERSION mdocPublishDeb
deploy:
  provider: bintray
  file: deploy.json
  user:
    secure: axr0zWQXpWolI84U4+ZmVIUJ/D44sfEhrAVPltUqe95EfEZsXjq6WNvEx2vzq50MjeWbgrwz4WX7QLqFpK9AdGW79LyFRTpEfa3RvE0+44YTVc0HDKN8cVfjG7tIAXpye/caoQ0OIRJY4SD+4OgNgO6SmMCUxpyY7BB02uu9uAQ=
  key:
    secure: NOEA682v6jnL5reIFf5nfD/bnLIG4lAruc0uI+JNljHLxZs3Y8G5g+UtsZXzlfgQDPatCfnpz5KprP9mjH34DlAf2UxXXXMLw5IfWQ87Wpwb4IJjN25UO0TgM4rAbLVGrajIYgovlh6bDJwYQQlHrTc5fWeIa6JO4gffuekN/ic=
after_deploy:
- cd scripts && sh cloud-install.sh

before_install:
- openssl aes-256-cbc -K $encrypted_110b31e51dff_key -iv $encrypted_110b31e51dff_iv
  -in scripts/cloud-identity.enc -out scripts/cloud-identity -d

env:
  global:
    secure: Y0RGqaShgPBUZNREz70IWikUkR2LNkBaCUtVJ/6Q0+whd2lsDHqrdW0ncI7q/Mq3GKcPVwB3ezbiDO3m9ZMFiTlqnv0bojtNZM4ul2WIFxeVGRSh2k+lFE8d6GDgweZ1s4W1IuSw/gkUJYZcXs/ygfTG9JonVTZN9e60By5SSvA=

notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/13627e9a6e8fa0dec084 # m-doc/general
    on_success: change
    on_failure: always
    on_start: never
